swagger: "2.0"
info:
  description: This is the swagger file that goes with our server code
  version: "1.0.0"
  title: Swagger REST Article
consumes:
  - "application/json"
produces:
  - "application/json"
security: []

basePath: "/api"

# Paths supported by the server application
paths:
  /ffd/accounts/<user>:
    get:
      operationId: "ffd.read"
      tags:
        - "Accounts"
      summary: "Returns the list of accounts accounts"
      description: "Read the list of accounts"
      responses:
        200:
          description: "Successful read the list of accounts"
          schema:
            type: "array"
            items:
              properties:
                id:
                  type: "integer"
                name:
                  type: "string"
                type:
                  type: "integer"
                comment:
                  type: "string"
  /ffd/:
    post:
      operationId: "ffd.send"
      tags:
        - "Actual Budget"
      summary: "Send new actuals and budgets to the server"
      description: "Send new actuals and budgets to the server"
      responses:
        200:
          description: "Successful send actuals and budgets"
          schema:
            type: "array"
            items:
              properties:
                type:
                  type: "string"
                userid:
                  type: "integer"
                groupid:
                  type: "integer"
                amount:
                  type: "integer"
                comment:
                  type: "string"
                level1:
                  type: "integer"
                level2:
                  type: "integer"
                level3:
                  type: "integer"
                costtype:
                  type: "integer"
                year:
                  type: "integer"
                month:
                  type: "integer"
                day:
                  type: "integer"
