swagger: "2.0"
info:
  description: This is the swagger file that goes with our server code
  version: "1.0.0"
  title: Swagger REST Article
consumes:
  - "application/json"
produces:
  - "application/json"
security: []

basePath: "/api"

# Paths supported by the server application
paths:
  /ffd/accounts/<level_type>:
    get:
      operationId: "ffd.readAccounts"
      tags:
        - "Accounts"
      summary: "Returns the list of accounts accounts"
      description: "Read the list of accounts"
      responses:
        200:
          description: "Successful read the list of accounts"
          schema:
            type: "array"
            items:
              properties:
                active:
                  type: "integer" 
                comment: 
                  type: "string"
                company_fk:
                  type: "integer"
                created: 
                  type: "string"
                created_by: 
                  type: "string"
                group_fk:
                  type: "integer"
                id: 
                  type: "integer"
                level_type: 
                  type: "integer"
                name: 
                  type: "string"
                parent_account: 
                  type: "integer"
                updated: 
                  type: "string"
                updated_by: 
                  type: "string"
                user_fk: 
                  type: "integer"
  /ffd/costtypes/:
    get:
      operationId: "ffd.readCosttypes"
      tags:
        - "Costtypes"
      summary: "Returns the list of costtypes"
      description: "Read the list of costtypes"
      responses:
        200:
          description: "Successful read the list of costtypes"
          schema:
            type: "array"
            items:
              properties:
                active:
                  type: "integer" 
                comment: 
                  type: "string"
                company_fk:
                  type: "integer"
                created: 
                  type: "string"
                created_by: 
                  type: "string"
                group_fk:
                  type: "integer"
                id: 
                  type: "integer"
                name: 
                  type: "string"
                parent_account: 
                  type: "integer"
                updated: 
                  type: "string"
                updated_by: 
                  type: "string"
                user_fk: 
                  type: "integer"
  /ffd/:
    post:
      operationId: "ffd.send"
      tags:
        - "Actual Budget"
      summary: "Send new actuals and budgets to the server"
      description: "Send new actuals and budgets to the server"
      responses:
        200:
          description: "Successful send actuals and budgets"
          schema:
            type: "array"
            items:
              properties:
                type:
                  type: "string"
                amount:
                  type: "string"
                userid:
                  type: "string"
                groupid:
                  type: "string"
                user:
                  type: "string"
                group:
                  type: "string"
                company:
                  type: "string"
                comment:
                  type: "string"
                level1id:
                  type: "string"
                level2id:
                  type: "string"
                level3id:
                  type: "string"
                level1:
                  type: "string"
                level2:
                  type: "string"
                level3:
                  type: "string"
                adminaccountlevel1id:
                  type: "string"
                adminaccountlevel2id:
                  type: "string"
                adminaccountlevel3id:
                  type: "string"
                adminaccountlevel1:
                  type: "string"
                adminaccountlevel2:
                  type: "string"
                adminaccountlevel3:
                  type: "string"
                accounttoaddlevel1:
                  type: "string"
                accounttoaddlevel2:
                  type: "string"
                accounttoaddlevel3:
                  type: "string"
                accounttoaddlevel1comment:
                  type: "string"
                accounttoaddlevel2comment:
                  type: "string"
                accounttoaddlevel3comment:
                  type: "string"
                accountfornewlevel2parentaccount:
                  type: "string"
                accountfornewlevel3parentaccount:
                  type: "string"
                costtypeid:
                  type: "string"
                costtype:
                  type: "string"
                costtypetoadd:
                  type: "string"
                costtypetoaddcomment:
                  type: "string"
                costtypetodeletedid:
                  type: "string"
                costtypetodelete:
                  type: "string"
                date:
                  type: "string"
                year:
                  type: "string"
                month:
                  type: "string"
                status:
                  type: "string"
