swagger: "2.0"
info:
  description: This is the swagger file that goes with our server code
  version: "1.0.0"
  title: Swagger REST Article
consumes:
  - "application/json"
produces:
  - "application/json"
security: []

basePath: "/api"

# Paths supported by the server application
paths:
  /ffd/accounts/<level_type>:
    get:
      operationId: "ffd.readAccounts"
      tags:
        - "Accounts"
      summary: "Returns the list of accounts accounts"
      description: "Read the list of accounts"
      responses:
        200:
          description: "Successful read the list of accounts"
          schema:
            type: "array"
            items:
              properties:
                active:
                  type: "integer" 
                comment: 
                  type: "string"
                company_fk:
                  type: "integer"
                created: 
                  type: "string"
                created_by: 
                  type: "string"
                group_fk:
                  type: "integer"
                id: 
                  type: "integer"
                level_type: 
                  type: "integer"
                name: 
                  type: "string"
                parent_account: 
                  type: "integer"
                updated: 
                  type: "string"
                updated_by: 
                  type: "string"
                user_fk: 
                  type: "integer"
  /ffd/preferences:
    get:
      operationId: "ffd.readPreferences"
      parameters:
        - in: query
          name: user
          type: string
          required: false
          description: Numeric ID of the user to get.
      tags:
        - "preferences"
      summary: "Returns the preferences"
      description: "Read the preferences"
      responses:
        200:
          description: "Successful read the list of preferences"
          schema:
            type: "array"
            items:
              properties:
                user_fk:
                  type: "integer"
                group_fk: 
                  type: "integer"
                company_fk:
                  type: "integer"
                costtypes_active:
                  type: "boolean"
                accounts_active:
                  type: "boolean"
                accountsLevel1_active:
                  type: "boolean"
                accountsLevel2_active:
                  type: "boolean"
                accountsLevel3_active:
                  type: "boolean"
  /ffd/costtypes/:
    get:
      operationId: "ffd.readCosttypes"
      tags:
        - "Costtypes"
      summary: "Returns the list of costtypes"
      description: "Read the list of costtypes"
      responses:
        200:
          description: "Successful read the list of costtypes"
          schema:
            type: "array"
            items:
              properties:
                active:
                  type: "integer" 
                comment: 
                  type: "string"
                company_fk:
                  type: "integer"
                created: 
                  type: "string"
                created_by: 
                  type: "string"
                group_fk:
                  type: "integer"
                id: 
                  type: "integer"
                name: 
                  type: "string"
                parent_account: 
                  type: "integer"
                updated: 
                  type: "string"
                updated_by: 
                  type: "string"
                user_fk: 
                  type: "integer"
  /ffd/amounts/:
    get:
      operationId: "ffd.readAmounts"
      #example: http://192.168.0.21:5000/api/ffd/amounts/?level_type=1&cost_type=-1&parent_account=-1&year=2019&month=2
      parameters:
        - in: query
          name: level_type
          type: integer
          required: false
          description: Numeric ID of the user to get.
        - in: query
          name: cost_type
          type: integer
          required: false
          description: Numeric ID of the user to get.
        - in: query
          name: parent_account
          type: integer
          required: false
          description: Numeric ID of the user to get.  
        - in: query
          name: year
          type: integer
          required: false
          description: Numeric ID of the user to get.  
        - in: query
          name: month
          type: integer
          required: false
          description: Numeric ID of the user to get.  
        - in: query
          name: _type
          type: string
          required: false
          description: actual or budget.  
      tags:
        - "Amounts"
      summary: "Returns the amounts per level and depending on costtype if specified"
      description: "Read the list of costtypes"
      responses:
        200:
          description: "Successful read the list of amounts"
          schema:
            type: "array"
            items:
              properties:
                active:
                  type: "integer" 
                comment: 
                  type: "string"
                company_fk:
                  type: "integer"
                created: 
                  type: "string"
                created_by: 
                  type: "string"
                group_fk:
                  type: "integer"
                id: 
                  type: "integer"
                name: 
                  type: "string"
                parent_account: 
                  type: "integer"
                updated: 
                  type: "string"
                updated_by: 
                  type: "string"
                user_fk: 
                  type: "integer"
  /ffd/amounts/:
    get:
      operationId: "ffd.readListActualBudget"
      #example: http://192.168.0.21:5000/api/ffd/amounts/?_type=1&user=-1&interval=-1
      parameters:
        - in: query
          name: _type
          type: string
          required: true
          description: actual or budget.
        - in: query
          name: user
          type: integer
          required: true
          description: Numeric ID of the user to get.
        - in: query
          name: interval
          type: integer
          required: false
          description: days back, default 365  
      tags:
        - "Amounts"
      summary: "Returns all actual or budget entries for the user in the interval"
      description: "Read the list of actual or budget entries for the user in the interval"
      responses:
        200:
          description: "Successful read the list of actual or budget entries for the user in the interval"
          schema:
            type: "array"
            items:
              properties:
                id:
                  type: "integer"
                amount:
                  type: "integer"
                comment:
                  type: "string"
                data_date:
                  type: "string"
                year: 
                  type: "integer"
                month:
                  type: "integer"
                day:
                  type: "string"
                level1:
                  type: "string"
                level1_fk:
                  type: "integer"
                level2:
                  type: "string"
                level2_fk:
                  type: "integer"
                level3:
                  type: "string"
                level3_fk:
                  type: "integer"
                costtype:
                  type: "string"
                costtype_fk:
                  type: "integer"
                user_fk:
                  type: "integer"
                group_fk:
                  type: "integer"
                created:
                  type: "string"
                updated:
                  type: "string"
                created_by:
                  type: "string"
                updated_by:
                  type: "string"
  /ffd/:
    post:
      operationId: "ffd.send"
      tags:
        - "Actual Budget Preferences Accounts"
      summary: "Send new actuals, budgets preferences and else to the server"
      description: "Send new actuals, budgets preferences and else to the server"
      responses:
        200:
          description: "Successful send actuals, budgets preferences and else"
          schema:
            type: "array"
            items:
              properties:
                type:
                  type: "string"
                amount:
                  type: "string"
                actualcomment:
                  type: "string"
                budgetcomment:
                  type: "string"
                userid:
                  type: "string"
                groupid:
                  type: "string"
                user:
                  type: "string"
                group:
                  type: "string"
                company:
                  type: "string"
                comment:
                  type: "string"
                level1id:
                  type: "string"
                level2id:
                  type: "string"
                level3id:
                  type: "string"
                level1:
                  type: "string"
                level2:
                  type: "string"
                level3:
                  type: "string"
                adminaccountlevel1id:
                  type: "string"
                adminaccountlevel2id:
                  type: "string"
                adminaccountlevel3id:
                  type: "string"
                adminaccountlevel1:
                  type: "string"
                adminaccountlevel2:
                  type: "string"
                adminaccountlevel3:
                  type: "string"
                accounttoaddlevel1:
                  type: "string"
                accounttoaddlevel2:
                  type: "string"
                accounttoaddlevel3:
                  type: "string"
                accounttoaddlevel1comment:
                  type: "string"
                accounttoaddlevel2comment:
                  type: "string"
                accounttoaddlevel3comment:
                  type: "string"
                accountfornewlevel2parentaccount:
                  type: "string"
                accountfornewlevel3parentaccount:
                  type: "string"
                costtypeid:
                  type: "string"
                costtype:
                  type: "string"
                costtypetoadd:
                  type: "string"
                costtypetoaddcomment:
                  type: "string"
                costtypetodeletedid:
                  type: "string"
                costtypetodelete:
                  type: "string"
                date:
                  type: "string"
                year:
                  type: "string"
                month:
                  type: "string"
                status:
                  type: "string"
                arecosttypesactive: 
                  type: "boolean"
                areaccountsactive: 
                  type: "boolean"
                arelevel1accountsactive: 
                  type: "boolean"
                arelevel2accountsactive: 
                  type: "boolean"
                arelevel3accountsactive: 
                  type: "boolean"
            
