version: '3.7'

services:
  postgres:
    container_name: postgres_ffd
    image: postgres
    restart: unless-stopped
    hostname: localhost
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=dhjihdfjdksfhdfhsdfj
    ports:
      - 5433:5432

volumes:
  pgdata:
    external: false

